
  CREATE TABLE "MYOMAMAUSER"."ACCOUNTING" 
   (	"TOTAL_PRICE" NUMBER, 
	"PATIENT_ID" CHAR(2 BYTE), 
	 CONSTRAINT "PATIENTID" FOREIGN KEY ("PATIENT_ID")
	  REFERENCES "MYOMAMAUSER"."PATIENT" ("PATIENTID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE TABLE "MYOMAMAUSER"."BANK" 
   (	"BLOODS_TYPE" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"NUMBER_UNIT" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE TABLE "MYOMAMAUSER"."DONORPERSON" 
   (	"PHONE" CHAR(10 BYTE), 
	"CITY" VARCHAR2(10 BYTE), 
	"FNAME" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"LNAME" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"DONOR_ID" CHAR(2 BYTE) NOT NULL ENABLE, 
	"AGE" VARCHAR2(3 BYTE), 
	"WEIGHT" VARCHAR2(3 BYTE), 
	"PATIENTID" CHAR(2 BYTE), 
	"BLOODGROUB" VARCHAR2(3 BYTE), 
	"NO_UNIT" VARCHAR2(2 BYTE), 
	 CONSTRAINT "PK_PATIEN" PRIMARY KEY ("DONOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE TABLE "MYOMAMAUSER"."PATIENT" 
   (	"FNAME" VARCHAR2(10 BYTE), 
	"LNAME" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"PHONE" CHAR(10 BYTE), 
	"AGE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"NUMBER_OF_UNIT" VARCHAR2(2 BYTE), 
	"PATIENTID" CHAR(2 BYTE) NOT NULL ENABLE, 
	"BLOOD_GROUP" CHAR(3 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PATIENT" PRIMARY KEY ("PATIENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
